### ISSUE TITLE
where can I download FluentData.dll ?

### ISSUE THREAD

**Issue by zbmcz** [tiesont/fluentdata#1]
where can I download FluentData.dll after codeplex closed ?

where is the official website for FluentData after codeplex closed ? Can I regard here as official ?

**Comment by zbmcz** [comment]
Thank you

**Comment by tiesont** [comment]
There isn't an official website for FluentData, as far as I know. I created https://tiesont.github.io/fluentdata/ because I use FluentData in a few OSS projects and needed a reference. The owner of the original CodePlex project hasn't ported it to Github, Bitbucket, etc. You could try asking him: https://twitter.com/kindblad

**Comment by tiesont** [comment]
I suppose I could compile the project and then add a zip package to the Releases tab. You're probably better off downloading the NuGet package, though: https://www.nuget.org/packages/FluentData/ - .nupkg files are just a container, so you can use something like 7zip to extract the files, if for some reason you can't use NuGet. This is the download link from NuGet: https://www.nuget.org/api/v2/package/FluentData/3.0.1

**Comment by zbmcz** [comment]
oh , thank you very much !
